import {createGame,act,visible,terrainVisible,reveal,visibleEnemy,floorAt,los,dist,idx,SIZE,itemName,validSave} from './engine.js';
import {VERSION,ENEMIES,ITEMS,WEAPONS,CHARMS,SKILLS,STATUS,phase} from './data.js';
import {LAYOUTS} from './dungeon.js';
const $=id=>document.getElementById(id),KEY='zanto-depths-save-v1',RECORD='zanto-depths-record-v1';
let state,record={best:1,wins:0,runs:0,known:[]},first=false,broken=false,overview=false,aim=null,selected=null,endShown=false,saving=true;
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(validSave(parsed))state=parsed;else{localStorage.setItem(KEY+'-unreadable-backup',raw);broken=true}}else first=true;const r=JSON.parse(localStorage.getItem(RECORD));if(r&&['best','wins','runs'].every(k=>Number.isFinite(r[k]))&&Array.isArray(r.known))record={...r,known:r.known.filter(k=>ENEMIES[k])}}catch{broken=true;saving=false}
state??=createGame();$('version').textContent='v'+VERSION;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(RECORD,JSON.stringify(record));saving=true}catch{saving=false}$('save').textContent=saving?'自動保存済み · seed '+state.seed:'保存できません · 書き出しを推奨'}
function modal(html){$('body').innerHTML=html;if(!$('modal').open)$('modal').showModal()}
function close(){$('modal').close()}
const canvas=$('map'),ctx=canvas.getContext('2d');let camera;
function draw(){
 const width=canvas.clientWidth,height=canvas.clientHeight,ratio=Math.min(devicePixelRatio||1,3);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle='#0b1115';ctx.fillRect(0,0,width,height);
 const cols=overview?SIZE:13,rows=overview?SIZE:11,tile=Math.min(width/cols,height/rows),left=overview?0:state.p.x-6,top=overview?0:state.p.y-5,ox=(width-cols*tile)/2,oy=(height-rows*tile)/2,vis=visible(state),terrain=terrainVisible(state);
 camera={left,top,tile,ox,oy};const on=(x,y)=>x>=left&&x<left+cols&&y>=top&&y<top+rows;
 function rect(x,y,color,inset=1){if(!on(x,y))return;ctx.fillStyle=color;ctx.fillRect(ox+(x-left)*tile+inset,oy+(y-top)*tile+inset,tile-inset*2,tile-inset*2)}
 function glyph(x,y,char,color,scale=.65){if(!on(x,y))return;ctx.fillStyle=color;ctx.font=`${Math.max(7,Math.floor(tile*scale))}px -apple-system,sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(char,ox+(x-left+.5)*tile,oy+(y-top+.53)*tile)}
 for(let y=Math.max(0,top);y<Math.min(SIZE,top+rows);y++)for(let x=Math.max(0,left);x<Math.min(SIZE,left+cols);x++){
  const k=idx(x,y);if(!state.seen[k])continue;const lit=terrain.has(k),wall=!state.map[k];
  rect(x,y,wall?(lit?'#727c7d':'#56646b'):(lit?((x+y)%2?'#303d40':'#2c383d'):'#23343f'),overview?0:1);
  if(wall){const px=ox+(x-left)*tile,py=oy+(y-top)*tile;ctx.strokeStyle=lit?'#d0d7c8':'#9aadb4';ctx.lineWidth=overview?1:1.5;ctx.beginPath();
   for(const[dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=SIZE||ny>=SIZE||!state.seen[idx(nx,ny)]||!state.map[idx(nx,ny)])continue;
    if(dy===-1){ctx.moveTo(px,py+1);ctx.lineTo(px+tile,py+1)}if(dy===1){ctx.moveTo(px,py+tile-1);ctx.lineTo(px+tile,py+tile-1)}if(dx===-1){ctx.moveTo(px+1,py);ctx.lineTo(px+1,py+tile)}if(dx===1){ctx.moveTo(px+tile-1,py);ctx.lineTo(px+tile-1,py+tile)}
   }ctx.stroke();
  }
 }
 for(const f of state.fields)if(vis.has(idx(f.x,f.y))){rect(f.x,f.y,({fire:'#9d4f3588',poison:'#5c814b99',smoke:'#939a9b66',ice:'#81b8d8aa'})[f.kind]);glyph(f.x,f.y,({fire:'炎',poison:'毒',smoke:'煙',ice:'氷'})[f.kind],'#d8d9c8',.45)}
 // Support influence is separate from impending damage.
 for(const e of state.enemies)if(e.type==='drummer'&&visibleEnemy(state,e)&&!e.status.silence)for(let y=e.y-3;y<=e.y+3;y++)for(let x=e.x-3;x<=e.x+3;x++)if(vis.has(idx(x,y))&&floorAt(state,x,y))rect(x,y,'#c2a25822');
 const warnings=[];for(const e of state.enemies)if(e.intent&&visibleEnemy(state,e))for(const p of e.intent.cells)warnings.push({...p,remaining:e.intent.remaining,kind:e.intent.kind});for(const b of state.blasts)for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)warnings.push({x:b.x+dx,y:b.y+dy,remaining:b.due-state.turn,kind:'blast'});
 for(const p of warnings)if(vis.has(idx(p.x,p.y))&&on(p.x,p.y)){const purple=['sleep','seal','teleport'].includes(p.kind);rect(p.x,p.y,purple?'#a681cc55':'#e2786055');if(!overview){const x=ox+(p.x-left)*tile,y=oy+(p.y-top)*tile;ctx.strokeStyle=purple?'#c5a2dd':'#d58d70';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+3,y+tile-3);ctx.lineTo(x+tile-3,y+3);ctx.stroke()}}
 if(state.seen[idx(state.stairs.x,state.stairs.y)])glyph(state.stairs.x,state.stairs.y,state.floor===20?'炉':'▤',state.enemies.some(e=>e.boss)?'#b57873':'#ecc17e',.8);
 for(const t of state.traps)if(t.revealed&&state.seen[idx(t.x,t.y)])glyph(t.x,t.y,'×','#e2aa98');
 for(const g of state.items)if(vis.has(idx(g.x,g.y)))glyph(g.x,g.y,ITEMS[g.item.type]?.glyph||'◇','#c3d7b8',.48);
 for(const e of state.enemies)if(visibleEnemy(state,e)||state.p.status.scout){const d=ENEMIES[e.type];glyph(e.x,e.y,d.glyph,d.color,e.boss?.85:.65);if(on(e.x,e.y)&&!overview){const x=ox+(e.x-left)*tile,y=oy+(e.y-top)*tile;ctx.fillStyle='#182026';ctx.fillRect(x+4,y+tile-4,tile-8,2);ctx.fillStyle=d.color;ctx.fillRect(x+4,y+tile-4,(tile-8)*Math.max(0,e.hp/e.maxHp),2);if(e.intent)glyph(e.x+.30,e.y-.26,String(e.intent.remaining),'#fff0bc',.4);if(e.type==='mirror'&&!e.status.silence&&state.turn%4<2)glyph(e.x+.28,e.y-.25,'◇','#e0f6ff',.4)}}
 glyph(state.p.x,state.p.y,'●','#ecc17e',.82);glyph(state.p.x,state.p.y,'·','#223239',.8);
 if(state.items.some(g=>g.x===state.p.x&&g.y===state.p.y))glyph(state.p.x+.28,state.p.y+.27,'◆','#d9eabf',.36);
 if(aim&&selected){const x=ox+(selected.x-left)*tile,y=oy+(selected.y-top)*tile;ctx.strokeStyle='#fff5c1';ctx.lineWidth=2;ctx.strokeRect(x+1,y+1,tile-2,tile-2)}
 canvas.setAttribute('aria-label',`地下${state.floor}階。生命${state.p.hp}。見える敵${state.enemies.filter(e=>visibleEnemy(state,e)).length}体。タップで調べる。`);
}
function render(){
 reveal(state);const p=state.p;$('floor').innerHTML=String(state.floor).padStart(2,'0')+' <span>/ 20</span>';$('hp').textContent=`${p.hp} / ${p.maxHp}`;$('hpbar').style.width=p.hp/p.maxHp*100+'%';$('hpbar').style.background=p.hp/p.maxHp<.3?'#f39383':'#9fc9b5';$('food').textContent='満腹 '+p.food+'%';$('loadout').textContent=`${WEAPONS[p.weapon].name}+${p.power} / 守${p.armor}`;$('ammo').textContent='矢 '+p.ammo;$('area').textContent=phase(state.floor)+' · '+(LAYOUTS[state.layout]||'主の間');$('turn').textContent=state.turn+' 手';$('bagcount').textContent=state.bag.length+'/16';$('points').textContent=p.points?'＋'+p.points:'';$('skills').classList.toggle('accent',p.points>0);
 $('stairs').textContent=state.floor===20?'✦ 灯炉を鎮める':'▤ 階段を降りる';$('stairs').disabled=state.status!=='playing'||dist(p,state.stairs)!==0||state.enemies.some(e=>e.boss);
 const ground=state.items.find(g=>g.x===p.x&&g.y===p.y);$('ground').hidden=!ground;$('ground').textContent=ground?'足元：'+itemName(ground.item)+(state.bag.length>=16?' / 袋で交換':' / 待つで拾う'):'';
 $('status-row').replaceChildren();for(const[key,turns]of Object.entries(p.status))if(turns>0){const b=document.createElement('button');b.textContent=(STATUS[key]?.split('：')[0]||key)+' '+turns;b.onclick=()=>modal(`<h2>現在の状態</h2><p>${esc(STATUS[key]||key)}</p><p>残り ${turns} 手</p>`);$('status-row').append(b)}
 $('log').replaceChildren(...state.logs.slice(0,3).map(text=>{const p=document.createElement('p');p.textContent=text;return p}));
 $('threats').replaceChildren();const enemies=state.enemies.filter(e=>visibleEnemy(state,e));for(const e of enemies){const b=document.createElement('button');b.textContent=ENEMIES[e.type].glyph+' '+ENEMIES[e.type].role+(e.intent?' · '+e.intent.remaining+'手':'');b.className=e.intent?'warn':'';b.onclick=()=>inspectEnemy(e.id);$('threats').append(b)}if(!enemies.length){const text=document.createElement('span');text.className='empty';text.textContent='敵・床をタップで調べる。閲覧中は時が止まる。';$('threats').append(text)}
 $('aim').hidden=!aim;draw();if(state.status!=='playing'&&!endShown){endShown=true;showEnd()}
}
function perform(action){if($('modal').open||aim||state.status!=='playing')return;const done=act(state,action);if(done){record.best=Math.max(record.best,state.floor);for(const type of state.known)if(!record.known.includes(type))record.known.push(type);if(state.status!=='playing'&&!state.recorded){state.recorded=true;record.runs++;if(state.status==='won')record.wins++}save()}render()}
function describeItem(item){if(item.type==='weapon')return WEAPONS[item.weapon].desc+' 近接基礎 '+(WEAPONS[item.weapon].atk+item.power);if(item.type==='armor')return '被ダメージを'+item.power+'軽減。毒・炎・飢えには無効。';if(item.type==='charm')return CHARMS[item.charm].desc;return ITEMS[item.type].desc+(item.charges?' 残り '+item.charges+'回。':'')}
function bag(){
 const ground=state.items.find(g=>g.x===state.p.x&&g.y===state.p.y);
 modal(`<h2>道具袋 <small>${state.bag.length} / 16</small></h2><p>使う・装備・置く・交換は1手。${state.p.status.seal?'現在、道具使用は封印されています。':''}</p><p>足元：${ground?esc(itemName(ground.item)):'なし'}</p><div id="inventory"></div>`);
 if(!state.bag.length)$('inventory').textContent='道具がありません。';
 state.bag.forEach((item,index)=>{const row=document.createElement('div');row.className='card';row.innerHTML=`<div class="card-head"><strong>${esc(itemName(item))}</strong><small>${item.charges?'残り'+item.charges+'回':''}</small></div><p>${esc(describeItem(item))}</p><div class="buttons"><button data-use>${ITEMS[item.type]?'使う':'装備'}</button><button data-drop>${ground?'交換':'置く'}</button></div>`;
 const use=row.querySelector('[data-use]');use.disabled=state.status!=='playing'||!!state.p.status.seal;use.onclick=()=>{close();const def=ITEMS[item.type];if(def&&def.kind!=='self')beginAim({type:'use',index});else perform({type:'use',index})};const drop=row.querySelector('[data-drop]');drop.disabled=state.status!=='playing';drop.onclick=()=>{close();perform({type:'drop',index})};$('inventory').append(row)});
}
function skills(){modal(`<h2>専門技能</h2><p>残り ${state.p.points} ポイント。各系統3段階まで。到達報酬：2・5・8・11・14・17階。習得はターンを消費しません。</p><div id="skill-list"></div><h3>装備</h3><p>${esc(WEAPONS[state.p.weapon].name)} +${state.p.power}<br>護りの外套 +${state.p.armor}<br>${esc(CHARMS[state.p.charm].name)} — ${esc(CHARMS[state.p.charm].desc)}</p>`);
 for(const[key,data]of Object.entries(SKILLS)){const row=document.createElement('div');row.className='card';row.innerHTML=`<div class="card-head"><strong>${data.name}</strong><small>${'●'.repeat(state.p.skills[key])}${'○'.repeat(3-state.p.skills[key])}</small></div><p>${data.desc}</p><div class="buttons"><button>習得</button></div>`;row.querySelector('button').disabled=state.p.points<1||state.p.skills[key]>=3||state.status!=='playing';row.querySelector('button').onclick=()=>{close();perform({type:'skill',skill:key});skills()};$('skill-list').append(row)}
}
function inspectEnemy(id){const e=state.enemies.find(v=>v.id===id);if(!e)return;const d=ENEMIES[e.type];modal(`<h2><span class="enemy-badge" style="color:${d.color}">${d.glyph}</span>${d.name}</h2><span class="role">${d.role}</span><p>生命 ${e.hp} / ${e.maxHp} · 基本攻撃 ${e.atk}</p><p>${d.tip}</p>${e.intent?`<p class="warning">予告中：あと${e.intent.remaining}手。地図の斜線の範囲を確認。</p>`:''}${e.type==='mirror'?`<p>${state.turn%4<2&&!e.status.silence?'現在は射撃を反射する。':'現在は反射しない。'}</p>`:''}<p>${Object.entries(e.status).filter(([,n])=>n>0).map(([k,n])=>esc((STATUS[k]?.split('：')[0]||k)+' '+n+'手')).join(' / ')||'状態異常なし'}</p><p>説明を読んでもターンは進みません。</p><button class="primary" id="target-enemy">この敵を狙う</button>`);$('target-enemy').disabled=state.status!=='playing';$('target-enemy').onclick=()=>{close();beginAim({type:'shoot'});chooseTarget({x:e.x,y:e.y})}}
function inspectTile(p){const e=state.enemies.find(e=>e.x===p.x&&e.y===p.y);if(e&&(visibleEnemy(state,e)||state.p.status.scout)){inspectEnemy(e.id);return}if(!state.seen[idx(p.x,p.y)])return;const g=state.items.find(g=>g.x===p.x&&g.y===p.y),trap=state.traps.find(t=>t.revealed&&t.x===p.x&&t.y===p.y),fields=state.fields.filter(f=>f.x===p.x&&f.y===p.y);modal(`<h2>${dist(p,state.stairs)===0?'階段':dist(p,state.p)===0?'あなたの足元':'地形を調べる'}</h2><p>${floorAt(state,p.x,p.y)?'移動できる床。':'壁・障壁。'}${g&&visible(state).has(idx(p.x,p.y))?'<br>落ちている道具：'+esc(itemName(g.item)):''}${trap?'<br>発見済みの'+(trap.kind==='spike'?'針':'毒')+'の罠。再度踏むと発動。':''}</p>${fields.map(f=>'<p>'+({fire:'炎：毎手3ダメージ。',poison:'毒床：毒を付与。',ice:'氷壁：通行・射線を遮る。',smoke:'煙：射線を遮る。'}[f.kind])+'残り約'+Math.max(0,f.until-state.turn)+'手。</p>').join('')}`)}
function beginAim(action){aim=action;selected=null;overview=false;$('overview').textContent='全体図 ↗';$('aim-confirm').disabled=true;const item=action.type==='use'?state.bag[action.index]:null;$('aim-text').textContent=item?itemName(item)+'：地図の対象をタップ → 実行':'射撃：地図の敵をタップ → 実行（槍は直線2マスなら近接）';render()}
function chooseTarget(p){selected=p;const item=aim.type==='use'?state.bag[aim.index]:null,def=item&&ITEMS[item.type];const e=state.enemies.find(v=>v.x===p.x&&v.y===p.y);const range=def?def.range:5+state.p.skills.ranged+(state.p.weapon==='bow'?1:0);const enemyRequired=!def||def.kind==='enemy';const valid=dist(state.p,p)<=range&&floorAt(state,p.x,p.y)&&los(state,state.p,p)&&(!enemyRequired||!!e);$('aim-confirm').disabled=!valid;$('aim-text').textContent=(item?itemName(item):'射撃')+' → '+(e?ENEMIES[e.type].name:`床 (${p.x},${p.y})`)+(valid?'。1手消費。実行しますか？':'：射程・射線・対象を確認。');draw()}
function cancelAim(){aim=null;selected=null;render()}
$('aim-confirm').onclick=()=>{if(!aim||!selected)return;const action={...aim,target:{...selected}},enemy=state.enemies.find(e=>e.x===selected.x&&e.y===selected.y);if(action.type==='shoot')action.id=enemy?.id;aim=null;selected=null;perform(action)};$('aim-cancel').onclick=cancelAim;
function showHelp(){modal(`<h2>残灯の深淵 <small>v${VERSION}</small></h2><p>敵を知り、退路を選び、最後の灯を守る。地下20階で残灯王を倒し、灯炉を鎮めれば帰還です。</p><p><a href="./update.html">最新版へ更新する</a></p><h3>一手の重み</h3><p>移動・近接・射撃・道具・装備は1手。壁への移動、説明の閲覧や照準取消は消費しません。敵をタップして特殊能力と対処を確認できます。斜線と数字は攻撃範囲と発動までの手数です。</p><p>方向パッドで移動、敵の方向へ進むと近接攻撃。防御はその手の被害を3軽減。足元の道具は「待つ」で拾い、袋から「置く・交換」ができます。袋は16枠です。</p><p>4手で満腹度−1。0になると毎手1ダメージ。空腹や毒でなければ10手に生命1回復。睡眠は次の1手を失い、被弾で解除。封印中も移動・射撃・置くは可能です。</p><h3>探索と成長</h3><p>2・5・8・11・14・17階で技能ポイント。全滅は不要。10・15・20階はボス撃破が必要です。能力や道具を惜しみすぎず、危険なら引き返しましょう。</p><p>近接・射撃とも壁の角は抜けられません。炎は敵味方に作用します。爆ぜ茸は倒した次の手の終了時に爆発します。召喚獣は討伐数に含みません。</p><h3>iPhoneと保存</h3><p>Safariの共有 → ホーム画面に追加。初回はオンラインで「オフライン準備完了」を確認。前作とは別の端末内保存です。複数タブの同時プレイは避けてください。</p><p>現在のseed：${state.seed}<br>最高到達 ${record.best}階 · 帰還 ${record.wins}回 · 終了した冒険 ${record.runs}回</p><p>PC：矢印 / HJKL、YUBNで斜め、Spaceで待機、Gで防御。文字入力中は操作しません。</p><button class="secondary" id="codex">敵図鑑と対処</button><button class="secondary" id="history">行動記録</button><button class="secondary" id="export">セーブを書き出す</button><button class="secondary" id="import">セーブを読み込む</button><input type="file" id="import-file" accept="application/json,.json" hidden><button class="secondary warning" id="new">新しい冒険</button><button class="primary" id="resume">迷宮へ戻る</button>`);
 $('resume').onclick=close;$('codex').onclick=showCodex;$('history').onclick=showHistory;$('new').onclick=()=>newRunDialog(false);$('export').onclick=exportSave;$('import').onclick=()=>$('import-file').click();$('import-file').onchange=importSave;
}
function showCodex(){modal('<h2>敵図鑑</h2><p>遭遇済みには「記録済み」を表示。未遭遇の敵も対処を読めます。</p>'+Object.entries(ENEMIES).map(([k,d])=>`<div class="card"><div class="card-head"><strong style="color:${d.color}">${d.glyph} ${d.name}</strong><small>${record.known.includes(k)?'記録済み':d.floor+'階～'}</small></div><p>${d.role} · ${d.tip}</p></div>`).join(''))}
function showHistory(){modal('<h2>行動記録</h2><div class="history">'+state.history.slice().reverse().map(h=>`<div>第${esc(h.turn)}手 · ${esc(h.action)} · 生命${esc(h.hp)}</div>`).join('')+'</div><h3>直近の出来事</h3><div class="history">'+state.logs.map(t=>'<div>'+esc(t)+'</div>').join('')+'</div>')}
function exportSave(){const blob=new Blob([JSON.stringify({game:'zanto-depths',state,record})],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='zanto-save-'+state.seed+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function importSave(event){const file=event.target.files?.[0];if(!file)return;try{if(file.size>1500000)throw Error();const parsed=JSON.parse(await file.text());if(parsed.game!=='zanto-depths'||!validSave(parsed.state))throw Error();modal('<h2>セーブを読み込む</h2><p>現在の冒険を選んだファイルの冒険に置き換えます。前作のセーブは読み込めません。</p><button class="primary" id="load">置き換える</button><button class="secondary" id="cancel-load">やめる</button>');$('cancel-load').onclick=showHelp;$('load').onclick=()=>{state=parsed.state;endShown=false;close();save();render()}}catch{modal('<h2>読み込めませんでした</h2><p>「残灯の深淵」の有効なセーブファイルを選んでください。</p>')}}
function newRunDialog(initial){modal(`<h2>${initial?'残灯の深淵':'新しい灯をともす'}</h2><p>${initial?'20階の戦術ローグライク。赤い予告を読み、支援役を見極め、無理なら逃げる。敵を調べる時間は無制限です。':'現在の冒険を終了して最初から始めます。端末内の攻略記録は残ります。'}</p><label for="seed">シード番号（空欄ならランダム）</label><input id="seed" inputmode="numeric" placeholder="例：20260925" maxlength="10"><p id="seed-error" class="warning"></p><button class="primary" id="begin">第1階へ</button>${initial?'':'<button class="secondary" id="cancel-new">今の冒険へ戻る</button>'}`);$('begin').onclick=()=>{const raw=$('seed').value.trim();if(raw&&!/^\d{1,10}$/.test(raw)||raw&&Number(raw)>4294967295){$('seed-error').textContent='0～4294967295の整数を入力してください。';return}state=createGame(raw?Number(raw):Date.now()>>>0);endShown=false;aim=null;overview=false;close();save();render()};if(!initial)$('cancel-new').onclick=close}
function showEnd(){modal(`<h2>${state.status==='won'?'灯は、まだ消えない。':'最後の一手を振り返る。'}</h2><p>${state.status==='won'?'残灯王を倒し、深淵の灯炉を鎮めました。':'死因：'+esc(state.cause||'生命を失った')}</p><p>地下${state.floor}階 · ${state.turn}手 · 討伐${state.kills}体<br>シード ${state.seed}</p><h3>直前の出来事</h3><div class="history">${(state.deathLog||state.logs).slice(0,8).map(t=>'<div>'+esc(t)+'</div>').join('')}</div><button class="primary" id="again">同じシードで再挑戦</button><button class="secondary" id="different">別の冒険を始める</button><button class="secondary" id="inspect">最後の戦場を見る</button>`);$('again').onclick=()=>{state=createGame(state.seed);endShown=false;close();save();render()};$('different').onclick=()=>newRunDialog(false);$('inspect').onclick=close}
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>perform({type:'move',...Object.fromEntries(['dx','dy'].map((k,i)=>[k,Number(b.dataset.move.split(',')[i])]))}));
$('wait').onclick=()=>perform({type:'wait'});$('guard').onclick=()=>perform({type:'guard'});$('stairs').onclick=()=>perform({type:'stairs'});$('shoot').onclick=()=>{if(state.status==='playing')beginAim({type:'shoot'})};$('bag').onclick=()=>{if(!aim)bag()};$('skills').onclick=()=>{if(!aim)skills()};$('help').onclick=showHelp;$('close').onclick=close;$('overview').onclick=()=>{if(aim)return;overview=!overview;$('overview').textContent=overview?'周辺図 ↙':'全体図 ↗';draw()};
canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left-camera.ox)/camera.tile)+camera.left,y=Math.floor((e.clientY-r.top-camera.oy)/camera.tile)+camera.top;if(x<0||y<0||x>=SIZE||y>=SIZE)return;if(aim)chooseTarget({x,y});else inspectTile({x,y})});
const keys={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],h:[-1,0],j:[0,1],k:[0,-1],l:[1,0],y:[-1,-1],u:[1,-1],b:[-1,1],n:[1,1]};document.addEventListener('keydown',e=>{if($('modal').open||e.ctrlKey||e.metaKey||e.altKey||['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='Escape'&&aim){cancelAim();return}if(keys[e.key]||[' ','g'].includes(e.key)){e.preventDefault();if(e.repeat)return;if(keys[e.key])perform({type:'move',dx:keys[e.key][0],dy:keys[e.key][1]});else perform({type:e.key==='g'?'guard':'wait'})}});
new ResizeObserver(draw).observe(canvas);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save()});window.addEventListener('pagehide',save);
render();if(first)newRunDialog(true);else if(broken)modal('<h2>セーブを確認できませんでした</h2><p>新しい冒険を準備しています。読み取りできなかった保存は可能な場合に別キーへ退避しました。書き出したセーブがあれば「?」から読み込めます。</p>');else save();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(()=>navigator.serviceWorker.ready).then(()=>{$('offline').textContent='オフライン準備完了'}).catch(()=>{$('offline').textContent='オフライン準備失敗 · 再読込'});else $('offline').textContent='オフライン非対応';
