import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,act,generate,spawn,validSave,idx,SIZE,dist,visible,makeItem} from '../engine.js';
import {ENEMIES,SKILLS} from '../data.js';
import {distances} from '../dungeon.js';
function arena(){const s=createGame(42);s.map=Array(SIZE*SIZE).fill(0);for(let y=1;y<SIZE-1;y++)for(let x=1;x<SIZE-1;x++)s.map[idx(x,y)]=1;s.enemies=[];s.items=[];s.traps=[];s.fields=[];s.blasts=[];s.p.x=15;s.p.y=15;return s}
function awake(s,type,x,y){const e=spawn(s,type,x,y);e.awake=true;e.alert=7;return e}
const wait=s=>act(s,{type:'wait'}),move=(s,dx,dy)=>act(s,{type:'move',dx,dy});
test('seed replays identical maps, enemies, loot and gameplay',()=>{const a=createGame(923),b=createGame(923);assert.deepEqual(a,b);wait(a);wait(b);assert.deepEqual(a,b)});
test('200 floors: connected stairs, safe arrival, guaranteed supplies, distinct valid save format',()=>{for(let seed=1;seed<=10;seed++){const s=createGame(seed);for(let floor=1;floor<=20;floor++){s.floor=floor;generate(s);const d=distances(s.map,s.p);assert.equal(d.filter(v=>v>=0).length,s.map.filter(Boolean).length);assert.ok(d[idx(s.stairs.x,s.stairs.y)]>=12);assert.ok(s.enemies.every(e=>dist(e,s.p)>5));assert.ok(s.items.filter(g=>g.item.type==='heal').length>=2);assert.ok(s.items.some(g=>g.item.type==='food'));assert.ok(validSave(JSON.parse(JSON.stringify(s))));assert.ok(s.enemies.some(e=>e.boss)===[10,15,20].includes(floor))}}});
test('archer telegraphs and fixed line can be dodged',()=>{const s=arena(),e=awake(s,'archer',15,11);wait(s);assert.equal(s.p.hp,42);assert.equal(e.intent.kind,'shot');assert.ok(e.intent.cells.some(p=>p.x===15&&p.y===15));move(s,1,0);assert.equal(s.p.hp,42);assert.equal(e.intent,null)});
test('archer hits if player ignores warning; guard reduces damage',()=>{const a=arena();awake(a,'archer',15,11);wait(a);wait(a);assert.equal(a.p.hp,38);const b=arena();awake(b,'archer',15,11);wait(b);act(b,{type:'guard'});assert.equal(b.p.hp,41)});
test('shield facing changes damage and opens after attack',()=>{const s=arena(),e=awake(s,'shield',15,14);e.face={x:0,y:1};move(s,0,-1);assert.equal(e.hp,16);assert.ok(e.open);const hp=e.hp;move(s,0,-1);assert.equal(e.hp,hp-7)});
test('rat pack damage is greater than isolated attack',()=>{const a=arena();awake(a,'rat',15,14);wait(a);const b=arena();awake(b,'rat',15,14);spawn(b,'rat',14,13);wait(b);assert.ok(b.p.hp<a.p.hp)});
test('sleep costs exactly one action and preserves the unused item',()=>{const s=arena();s.p.status.sleep=1;const bag=structuredClone(s.bag);act(s,{type:'use',index:0});assert.equal(s.turn,1);assert.deepEqual(s.bag,bag);assert.ok(s.p.status.sleepImmune);assert.equal(s.p.status.sleep,undefined)});
test('seal blocks items but allows shooting and dropping',()=>{const s=arena();s.p.status.seal=3;assert.equal(act(s,{type:'use',index:0}),false);assert.equal(s.turn,0);assert.equal(act(s,{type:'drop',index:0}),true);const e=awake(s,'rat',15,11);assert.equal(act(s,{type:'shoot',id:e.id}),true)});
test('poison and starvation bypass armor and guard',()=>{const s=arena();s.p.armor=3;s.p.status.poison=2;s.p.food=0;act(s,{type:'guard'});assert.equal(s.p.hp,40)});
test('healer restores ally; silence prevents heal and pending spell',()=>{const s=arena(),healer=awake(s,'healer',13,13),rat=awake(s,'rat',13,14);rat.hp=1;wait(s);assert.equal(rat.hp,7);healer.cd=0;healer.status.silence=1;wait(s);assert.equal(rat.hp,7);const monk=awake(s,'monk',17,15);monk.intent={kind:'seal',cells:[{x:15,y:15}],remaining:1,damage:0};s.bag=[makeItem('silence')];act(s,{type:'use',index:0,target:{x:17,y:15}});assert.equal(monk.intent,null);assert.equal(s.p.status.seal,undefined)});
test('fungus delayed explosion hits allies, has escape window',()=>{const s=arena(),e=awake(s,'fungus',15,14);e.hp=1;const ally=spawn(s,'shield',14,13);move(s,0,-1);assert.equal(s.p.hp,42);assert.equal(s.blasts.length,1);move(s,0,1);assert.equal(s.p.hp,42);assert.ok(ally.hp<ally.maxHp);assert.equal(s.blasts.length,0)});
test('mirror reflects shots only during reflective phase',()=>{const s=arena(),e=awake(s,'mirror',15,12);act(s,{type:'shoot',id:e.id});assert.equal(e.hp,e.maxHp);assert.equal(s.p.hp,36);s.turn=2;const before=e.hp;act(s,{type:'shoot',id:e.id});assert.equal(e.hp,before-6)});
test('pull and anchor charm change positional danger',()=>{const s=arena(),e=awake(s,'chain',15,11);wait(s);wait(s);assert.equal(s.p.y,13);const a=arena();a.p.charm='anchor';awake(a,'chain',15,11);wait(a);wait(a);assert.equal(a.p.y,15)});
test('summoner has finite budget and summons have no kill score',()=>{const s=arena(),e=awake(s,'caller',15,12);e.calls=3;wait(s);assert.notEqual(e.intent?.kind,'summon');s.enemies=[];const rat=spawn(s,'rat',15,14,true);rat.hp=1;move(s,0,-1);assert.equal(s.kills,0)});
test('growth starts after contact; newly seen enemy gives reaction turn',()=>{const s=arena(),e=spawn(s,'sprout',15,10);wait(s);assert.equal(e.age,0);for(let n=0;n<6;n++)wait(s);assert.equal(e.age,6);assert.ok(e.maxHp>ENEMIES.sprout.hp);assert.ok(s.fields.some(f=>f.kind==='poison'))});
test('skills cost points, not turns; drops/exchanges do not use effects',()=>{const s=arena();s.p.points=1;act(s,{type:'skill',skill:'ranged'});assert.equal(s.turn,0);assert.equal(s.p.skills.ranged,1);assert.equal(act(s,{type:'skill',skill:'ranged'}),false);s.p.hp=10;s.bag=[makeItem('heal')];act(s,{type:'drop',index:0});assert.equal(s.p.hp,10);s.bag=[makeItem('food')];act(s,{type:'drop',index:0});assert.equal(s.bag[0].type,'heal');assert.equal(s.items[0].item.type,'food')});
test('wand charges and item specialist conserve limited resources',()=>{const s=arena(),e=awake(s,'executioner',15,10);s.bag=[makeItem('wand')];e.stun=10;s.p.skills.tools=2;act(s,{type:'use',index:0,target:{x:e.x,y:e.y}});assert.equal(s.bag[0].charges,3);act(s,{type:'use',index:0,target:{x:e.x,y:e.y}});assert.equal(s.bag[0].charges,2)});
test('invalid targets do not consume a turn or item',()=>{const s=arena();s.bag=[makeItem('blink')];const before=structuredClone(s.bag);assert.equal(act(s,{type:'use',index:0,target:{x:29,y:29}}),false);assert.equal(s.turn,0);assert.deepEqual(s.bag,before);assert.equal(act(s,{type:'move',dx:2,dy:0}),false)});
test('boss locks stairs, final clear requires boss defeated and exit action',()=>{const s=createGame(1);s.floor=20;generate(s);s.p.x=s.stairs.x;s.p.y=s.stairs.y;assert.equal(act(s,{type:'stairs'}),false);s.enemies=[];assert.equal(act(s,{type:'stairs'}),true);assert.equal(s.status,'won');assert.equal(act(s,{type:'wait'}),false)});
test('boss special attacks and all enemy types survive turn/save simulation',()=>{for(const type of Object.keys(ENEMIES)){const s=arena();s.p.hp=100;s.p.maxHp=100;const e=awake(s,type,15,12);for(let n=0;n<8&&s.status==='playing';n++)wait(s);assert.ok(validSave(JSON.parse(JSON.stringify(s))),type)}});
test('fifty mixed-action simulations have no crashes or invalid saves',()=>{for(let seed=1;seed<=50;seed++){const s=createGame(seed);for(let n=0;n<100&&s.status==='playing';n++){const dx=(n*seed%3)-1,dy=(n*7%3)-1;act(s,dx||dy?{type:'move',dx,dy}:{type:'guard'});assert.ok(validSave(s))}}});

